@WebAPI_HostAddress = http://localhost:5021

GET {{WebAPI_HostAddress}}/api/categories
Accept: application/json

###

POST {{WebAPI_HostAddress}}/api/categories
Content-Type: application/json

{ "name": "Electronics", "description": "Electronic products" }

###

GET {{WebAPI_HostAddress}}/api/categories/1/products-count

###

POST {{WebAPI_HostAddress}}/api/products
Content-Type: application/json

{ "categoryId": 1, "name": "Laptop", "description": "Gaming laptop", "price": 1200, "quantity": 5 }

###

GET {{WebAPI_HostAddress}}/api/products?pageNumber=1&pageSize=10

###

GET {{WebAPI_HostAddress}}/api/products/category/1

###

GET {{WebAPI_HostAddress}}/api/products/search?name=laptop
